version: "3.9"

services:
  app:
    container_name: "app_container"
    image: "app:1.0"
    env_file:
      - ./.env
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=${DB_SERVER}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    container_name: "db_container"
    image: postgres:13-alpine
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  db-data:
